sudo: false

os:
 - linux

language: d

d:
 - dmd-2.077.0
 - dmd-2.076.0
 - ldc-1.5.0

env: 
  matrix:
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
- dub test --arch=$ARCH
